version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "13:00"
    groups:
      python-packages:
        patterns:
          - "*"
    ignore:
      - dependency-name: "quarto-cli"
        versions: [">=1.6.0"]
      - dependency-name: "ruff"
        versions: [">=0.9.5"]
      - dependency-name: "textual"
        versions: [">=2.0.0"]
      - dependency-name: "rich"
        versions: [">=14.0.0"]
      - dependency-name: "fsspec"
        versions: [">=2024.12.0"]
